include: package:flutter_lints/flutter.yaml
linter:
  rules:
    # https://dart.dev/tools/linter-rules#prefer-const-constructors
    prefer_const_constructors: true
    # https://dart.dev/tools/linter-rules#prefer-const-literals
    prefer_const_literals_to_create_immutables: true
    # https://dart.dev/tools/linter-rules#prefer-final-parameters
    prefer_final_parameters: falset
